import http from 'node:http'; import fs from 'node:fs'; import path from 'node:path';
const PORT=Number(process.env.PORT||8765), HOST=process.env.HOST||'0.0.0.0', DATA=process.env.DATA_DIR||path.resolve('data'); fs.mkdirSync(DATA,{recursive:true});
const initial={version:'R5.0-dev.1',tick:0,power:true,wifi:true,guest:{x:1,z:4,mood:80,goal:'ride'},ride:{x:0,z:0,running:true,angle:0,queue:0},events:[]};
const file=path.join(DATA,'world.json'); let world=fs.existsSync(file)?JSON.parse(fs.readFileSync(file,'utf8')):structuredClone(initial);
function applyRules(){world.ride.running=!!world.power;if(!world.wifi) world.guest.mood=Math.max(0,world.guest.mood-.05);world.ride.angle=(world.ride.angle+(world.ride.running?1.4:0))%360;world.guest.x=3*Math.sin(world.tick/50);world.guest.z=3*Math.cos(world.tick/50);world.tick++;}
setInterval(()=>{applyRules();},100);
const page=`<!doctype html><html><head><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><title>R5 dev.1</title><style>html,body{margin:0;height:100%;background:#101419;color:#e9eef5;font:14px system-ui}#bar{position:fixed;z-index:2;padding:12px;background:#151c24dd;border-radius:0 0 12px 0}button{margin:3px;padding:8px}canvas{width:100%;height:100%;display:block}</style></head><body><div id=bar><b>R5 miniature world</b><br><button onclick="cmd('power')">Toggle power</button><button onclick="cmd('wifi')">Toggle Wi-Fi</button><button onclick="cmd('save')">Save</button><button onclick="cmd('reset')">Reset</button><pre id=s></pre></div><canvas id=c></canvas><script>
const c=document.querySelector('#c'),x=c.getContext('2d'),s=document.querySelector('#s');function resize(){c.width=innerWidth*devicePixelRatio;c.height=innerHeight*devicePixelRatio}onresize=resize;resize();async function cmd(a){await fetch('/api/command',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:a})})}async function frame(){let w=await (await fetch('/api/world')).json();s.textContent='power: '+w.power+' | wifi: '+w.wifi+' | mood: '+w.guest.mood.toFixed(0)+' | ride: '+w.ride.running;x.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);x.clearRect(0,0,innerWidth,innerHeight);x.fillStyle='#172b20';x.fillRect(0,0,innerWidth,innerHeight);let cx=innerWidth/2,cy=innerHeight/2;x.strokeStyle='#9aa4ad';x.lineWidth=24;x.beginPath();x.arc(cx,cy,150,0,Math.PI*2);x.stroke();x.save();x.translate(cx,cy);x.rotate(w.ride.angle*Math.PI/180);x.strokeStyle=w.ride.running?'#e8c15b':'#7d8288';x.lineWidth=10;x.beginPath();x.moveTo(-80,0);x.lineTo(80,0);x.stroke();x.fillStyle='#dfe8ef';x.fillRect(-95,-12,25,24);x.fillRect(70,-12,25,24);x.restore();x.fillStyle=w.wifi?'#68b8ff':'#59616a';x.beginPath();x.arc(cx+220,cy-120,18,0,7);x.fill();x.fillStyle='#ffcf73';x.beginPath();x.arc(cx+w.guest.x*50,cy+w.guest.z*50,9,0,7);x.fill();requestAnimationFrame(frame)}frame();</script></body></html>`;
const server=http.createServer(async(req,res)=>{if(req.url==='/api/world'){res.setHeader('content-type','application/json');return res.end(JSON.stringify(world))}if(req.url==='/health'){return res.end('ok')}if(req.url==='/api/command'&&req.method==='POST'){let b='';for await(const ch of req)b+=ch;let {action}=JSON.parse(b||'{}');if(action==='power')world.power=!world.power;if(action==='wifi')world.wifi=!world.wifi;if(action==='save')fs.writeFileSync(file,JSON.stringify(world,null,2));if(action==='reset'){world=structuredClone(initial);fs.writeFileSync(file,JSON.stringify(world,null,2))}world.events.push({tick:world.tick,action});res.setHeader('content-type','application/json');return res.end(JSON.stringify({ok:true,world}))}res.setHeader('content-type','text/html');res.end(page)});server.listen(PORT,HOST,()=>console.log(`R5 listening on http://${HOST}:${PORT}`));
