spring.main.web-application-type=none

loa.indexer.batch-size=10
loa.indexer.parallelism=2

loa.conductor.host=127.0.0.1
loa.conductor.port=8092
loa.conductor.application-type=INDEXER_APPLICATION
loa.conductor.application-port=0

spring.codec.max-in-memory-size=-1
loa.compression.algorithm=none
