import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';

const PORT=Number(process.env.PORT||8765), HOST=process.env.HOST||'0.0.0.0';
const DATA=process.env.DATA_DIR||path.resolve('data'), CODEX_PATH=process.env.CODEX_PATH||'/codex/codex.json';
fs.mkdirSync(DATA,{recursive:true});
if(!fs.existsSync(CODEX_PATH)){console.error(`📕 R5 startup blocked: Codex not found at ${CODEX_PATH}`);process.exit(2)}
let codex; try{codex=JSON.parse(fs.readFileSync(CODEX_PATH,'utf8'))}catch(e){console.error(`📕 R5 startup blocked: invalid Codex JSON: ${e.message}`);process.exit(2)}

const verses=[];
for(const [book,chapters] of Object.entries(codex)) for(const [chapter,units] of Object.entries(chapters||{})) for(const [verse,text] of Object.entries(units||{})) if(typeof text==='string'&&text.trim()) verses.push({id:`${book}.${chapter}.${verse}`,reference:`${book} ${chapter}:${verse}`,text});
if(!verses.length){console.error('📕 R5 startup blocked: Codex contains no addressable verse units');process.exit(2)}
const randomVerse=()=>verses[Math.floor(Math.random()*verses.length)];
const reflection=v=>({unitId:v.id,reference:v.reference,text:v.text,wisdom:`Ava is reflecting on ${v.reference} and preserving it as this iteration’s perceived wisdom.`});
const initial=()=>({version:'R5.0-dev.5',tick:0,simulationRunning:true,codexAvailable:true,entity:{id:'ava',name:'Ava',role:'observer-learner',timeline:0,happiness:55,wisdom:0,lastPerception:null,iterationReflection:null,memory:[]},events:[]});
const file=path.join(DATA,'world.json');
let loaded=null; try{loaded=fs.existsSync(file)?JSON.parse(fs.readFileSync(file,'utf8')):null}catch{}
let world=loaded?.version==='R5.0-dev.5'?loaded:initial();
world.entity.memory??=[]; world.entity.id='ava'; world.entity.name='Ava'; world.entity.role='observer-learner';
function remember(kind,detail){world.entity.memory.push({at:new Date().toISOString(),tick:world.tick,kind,detail});if(world.entity.memory.length>100)world.entity.memory.splice(0,world.entity.memory.length-100)}
function beginIteration(reason='startup'){const v=randomVerse();world.entity.iterationReflection=reflection(v);world.entity.lastPerception=world.codexAvailable?reflection(v):null;remember('iteration-reflection',{reason,reference:v.reference,unitId:v.id});}
beginIteration('startup');
function perceive(){if(!world.codexAvailable){world.entity.lastPerception=null;return} world.entity.lastPerception=world.entity.iterationReflection;world.entity.wisdom=Math.min(100,world.entity.wisdom+.12)}
function applyRules(){if(!world.simulationRunning)return;world.tick++;world.entity.timeline=(world.entity.timeline+.006)%1;if(world.codexAvailable){perceive();world.entity.happiness=Math.min(100,world.entity.happiness+.08)}else world.entity.happiness=Math.max(0,world.entity.happiness-.06)}
setInterval(applyRules,100);
const page=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>R5 dev.5 • Ava observer</title><style>html,body{margin:0;min-height:100%;background:#101419;color:#e9eef5;font:14px system-ui}#bar{position:fixed;z-index:2;padding:14px;background:#151c24ee;border-radius:0 0 14px 0;max-width:min(620px,calc(100% - 28px))}button{margin:3px;padding:9px 12px}.wisdom{white-space:pre-wrap;color:#d7e4cf;max-width:590px}canvas{width:100%;height:100%;position:fixed;inset:0}</style></head><body><div id="bar"><b>R5 miniature world • Ava observer</b><br><button id="sim"></button><button id="codex"></button><button onclick="cmd('save')">Save</button><button onclick="cmd('reset')">Reset iteration</button><pre id="s"></pre><div class="wisdom" id="w"></div></div><canvas id="c"></canvas><script>
const c=document.querySelector('#c'),x=c.getContext('2d'),s=document.querySelector('#s'),w=document.querySelector('#w'),sim=document.querySelector('#sim'),cod=document.querySelector('#codex');function resize(){c.width=innerWidth*devicePixelRatio;c.height=innerHeight*devicePixelRatio}onresize=resize;resize();async function cmd(action){await fetch('/api/command',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action})})}sim.onclick=()=>cmd('simulation');cod.onclick=()=>cmd('codex');async function frame(){const v=await(await fetch('/api/world')).json();sim.textContent=v.simulationRunning?'⏸ Stop simulation':'▶ Start simulation';cod.textContent=v.codexAvailable?'📖 Codex available':'📕 Codex unavailable';s.textContent='Ava • tick '+v.tick+' • happiness '+v.entity.happiness.toFixed(0)+' • wisdom '+v.entity.wisdom.toFixed(0)+' • memories '+v.entity.memory.length;const p=v.entity.lastPerception;w.textContent=p?'Iteration reflection: '+p.reference+'\n“'+p.text+'”\n'+p.wisdom:'Ava cannot currently perceive her iteration verse.';x.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);x.clearRect(0,0,innerWidth,innerHeight);x.fillStyle='#172b20';x.fillRect(0,0,innerWidth,innerHeight);let cx=innerWidth/2,cy=innerHeight/2;x.strokeStyle='#8d989e';x.lineWidth=18;x.beginPath();x.arc(cx,cy,150,0,Math.PI*2);x.stroke();let a=v.entity.timeline*Math.PI*2-Math.PI/2;x.fillStyle=v.entity.happiness>60?'#f5d46f':'#d3a46b';x.beginPath();x.arc(cx+Math.cos(a)*150,cy+Math.sin(a)*150,12,0,Math.PI*2);x.fill();x.fillStyle=v.codexAvailable?'#d7e4cf':'#59616a';x.fillRect(cx-30,cy-22,60,44);x.fillStyle='#101419';x.textAlign='center';x.fillText('CODEX',cx,cy+4);requestAnimationFrame(frame)}frame();</script></body></html>`;
const server=http.createServer(async(req,res)=>{if(req.url==='/health'){res.setHeader('content-type','application/json');return res.end(JSON.stringify({ok:true,version:world.version,codexUnits:verses.length,entity:'Ava'}))}if(req.url==='/api/world'){res.setHeader('content-type','application/json');return res.end(JSON.stringify(world))}if(req.url==='/api/codex/status'){res.setHeader('content-type','application/json');return res.end(JSON.stringify({available:true,path:CODEX_PATH,units:verses.length}))}if(req.url==='/api/command'&&req.method==='POST'){let b='';for await(const ch of req)b+=ch;let {action}=JSON.parse(b||'{}');if(action==='simulation'){world.simulationRunning=!world.simulationRunning;remember('simulation',world.simulationRunning?'started':'stopped')}if(action==='codex'){world.codexAvailable=!world.codexAvailable;if(world.codexAvailable)perceive();else world.entity.lastPerception=null;remember('codex',world.codexAvailable?'available':'unavailable')}if(action==='save'){fs.writeFileSync(file,JSON.stringify(world,null,2));remember('save','world saved')}if(action==='reset'){const oldMemory=world.entity.memory;world=initial();world.entity.memory=oldMemory;beginIteration('reset');fs.writeFileSync(file,JSON.stringify(world,null,2))}world.events.push({tick:world.tick,action});res.setHeader('content-type','application/json');return res.end(JSON.stringify({ok:true,world}))}res.setHeader('content-type','text/html');res.end(page)});
server.listen(PORT,HOST,()=>console.log(`🎡 R5 dev.5 listening on http://${HOST}:${PORT} • 📖 ${verses.length} Codex verse units • 👁 Ava observing`));
