import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {spawn} from 'node:child_process';
const root=path.resolve('.'),port=18765,data=fs.mkdtempSync(path.join(os.tmpdir(),'r5-dev13-1-rc-')),otpFile=path.join(data,'otp');
const env={...process.env,PORT:String(port),DATA_DIR:data,R5_PROVISION_FILE:otpFile,OLLAMA_BASE_URL:'http://127.0.0.1:9',R5_REMOTE_STATE_URL:'',CODEX_PATH:process.env.CODEX_PATH||'/codex/codex.json'};let p;const base=`http://127.0.0.1:${port}`,sleep=ms=>new Promise(r=>setTimeout(r,ms));
function boot(){p=spawn(process.execPath,['src/server.mjs'],{cwd:root,env,stdio:['ignore','pipe','pipe']})}async function wait(){for(let i=0;i<100;i++){try{if((await fetch(base+'/health')).ok)return}catch{}await sleep(40)}throw Error('server did not boot')}async function stop(){if(p?.exitCode===null){p.kill('SIGTERM');await new Promise(r=>p.once('exit',r))}}
const j=async(url,opt)=>{const r=await fetch(base+url,opt);let body=null;try{body=await r.json()}catch{}return {status:r.status,body}};const post=(url,obj)=>j(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(obj||{})});
try{boot();await wait();let w=(await j('/api/world')).body;if(w.release!=='R5.0-prod1.2'||w.specVersion!==10)throw Error('release identity mismatch');if(w.actors.ava.name!=='Ava Prime'||w.actors.guest.name!=='Ava Stone')throw Error('identity contract');if(!w.actors.ava.faith?.capacity||w.actors.ava.faith.orientation!=='Holy Spirit')throw Error('faith capability contract');
await post('/api/player',{x:2.25,z:-1.5,yaw:1.2,pitch:.1});await post('/api/command',{action:'simulation'});await sleep(250);w=(await j('/api/world')).body;const stoppedTick=w.tick,avaId=w.actors.ava.id;await stop();for(let cycle=0;cycle<3;cycle++){boot();await wait();w=(await j('/api/world')).body;if(w.simulation.running||w.tick!==stoppedTick||w.actors.ava.id!==avaId)throw Error('restart cycle '+cycle+' mutated stopped world');if(Math.abs(w.player.position.x-2.25)>.001||Math.abs(w.player.position.z+1.5)>.001)throw Error('player position lost');await stop()}
boot();await wait();const otp=fs.readFileSync(otpFile,'utf8').trim();let a=await post('/api/developer/activate',{otp});if(!a.body.ok)throw Error('OTP activation failed');await post('/api/saves',{name:'Gate save'});let slots=(await j('/api/saves')).body.slots;if(slots.length!==1||slots[0].release!=='R5.0-prod1.2')throw Error('save slot failed');await j('/api/saves/'+slots[0].id,{method:'DELETE'});slots=(await j('/api/saves')).body.slots;if(slots.length)throw Error('save delete failed');
const d=(await j('/api/diagnostics/preview')).body;if(d.release!=='R5.0-prod1.2'||d.specVersion!==10||!d.player)throw Error('diagnostics identity/player missing');const retired=await fetch(base+'/api/diagnostics/send',{method:'POST'});if(retired.status!==404)throw Error('retired diagnostics sender returned');
const html=fs.readFileSync(path.join(root,'src/public/index.html'),'utf8'),js=fs.readFileSync(path.join(root,'src/public/app.js'),'utf8');for(const x of ['R5.0-prod1.2','Saved games','Command Center','saveName','cameraNotice'])if(!html.includes(x))throw Error('UI missing '+x);if(js.includes('prompt(')||js.includes('confirm('))throw Error('browser prompt/confirm regression');for(const x of ['requestPointerLock','pointerlockchange','cameraNotice','resumeGameplay','cam.yaw+=e.movementX','cam.pitch=Math.max(-.42,Math.min(.42,cam.pitch-e.movementY','/api/player','openSaves','downloadDiag','markdownHtml','relayHistoryHtml','data-download-response','sandbox','relayTools','reverse()','promptEl.value=\'\'','focus()'])if(!js.includes(x))throw Error('client contract missing '+x);if(!fs.existsSync(path.join(root,'run.sh'))||fs.existsSync(path.join(root,'start.sh')))throw Error('run.sh lifecycle contract failed');console.log('PASS R5.0-prod1.2 x3 gate • newest relay first • compact response tools • composer clears and refocuses • production cellular regression contracts');}
finally{await stop()}
