loa.queue.port=61616

spring.artemis.embedded.enabled=false

loa.conductor.host=127.0.0.1
loa.conductor.port=8092
loa.conductor.application-type=QUEUE_APPLICATION
loa.conductor.application-port=61616

spring.main.web-application-type=none

# Artemis persistent queue storage
loa.queue.data-directory=/home/hstone/Documents/games/rollamacoaster-tycoon/loa-runtime/queue/data
