server.port=8093
server.error.include-message=always

spring.rsocket.server.port=8093
spring.rsocket.server.fragment-size=8MB

loa.conductor.host=127.0.0.1
loa.conductor.port=8092
loa.conductor.application-type=VAULT_APPLICATION
loa.conductor.application-port=8093

loa.vault.name=rct-dev
loa.vault.archiving=true
loa.vault.parallelism=4
loa.vault.modification-enabled=true
loa.vault.version-number=7

loa.vault.staging-directory=/home/hstone/Documents/games/rollamacoaster-tycoon/loa-runtime/vault/staging

loa.compression.algorithm=NONE

# Persistent document vault
loa.vault.location.sqlite.path=/home/hstone/Documents/games/rollamacoaster-tycoon/loa-runtime/vault/archive
loa.vault.location.sqlite.batch-size=100000

# Compatibility with current LoA Vault bean graph

# Force Vault HTTP document API to bind
spring.main.web-application-type=servlet
server.address=0.0.0.0
