server.port=8090
server.error.include-message=always

loa.conductor.host=127.0.0.1
loa.conductor.port=8092
loa.conductor.application-type=WEB_APPLICATION
loa.conductor.application-port=8090

loa.compression.algorithm=none
loa.user.enabled=false

# RCT local LoA web/API runtime
spring.main.web-application-type=servlet
server.address=127.0.0.1
