spring.main.web-application-type=none

loa.conductor.host=127.0.0.1
loa.conductor.port=8092
loa.conductor.application-type=DOWNLOADER_APPLICATION
loa.conductor.application-port=0

loa.downloader.parallelism=2
loa.downloader.version-number=7

loa.downloader.source=folder
loa.downloader.source.folder.location=/home/hstone/Documents/games/rollamacoaster-tycoon/loa-runtime/import/inbox
loa.downloader.source.folder.source-name=rct-local-import
loa.downloader.source.folder.should-remove=false

loa.downloader.staging-directory=/home/hstone/Documents/games/rollamacoaster-tycoon/loa-runtime/downloader-work

loa.http.parallelism=2
loa.checksum.type=sha256
loa.validation.maximum-archive-size=8589934592

loa.compression.algorithm=NONE
